### ISSUE TITLE
Selection and document highlight nearly invisible

### ISSUE THREAD

**Issue by leo-carmo** [AdsonCicilioti/yaru-vscode#1]
Hi, congratulations for your nice theme!
A small remark I should point out is the fact that the selection color is almost the same as the background color, hence making it difficult for the weary eyes to tell what's selected. The same applies to the right-side miniview highlight. 
Please consider fixing it! :)

**Comment by AdsonCicilioti** [comment]
Thanks @leo-carmo !
Fix in-progress now!
